.c9/metadata/workspace/jb/urls.py
{"filter":false,"title":"urls.py","tooltip":"/jb/urls.py","undoManager":{"stack":[],"mark":-1,"position":-1},"ace":{"folds":[],"scrolltop":0,"scrollleft":0,"selection":{"start":{"row":10,"column":1},"end":{"row":10,"column":1},"isBackwards":false},"options":{"guessTabSize":true,"useWrapMode":false,"wrapToView":true},"firstLineState":0},"timestamp":1429797495736,"hash":"04c77886bdce2dec0525f5e0fac419d775b32938"}

.c9/metadata/workspace/jobbank/urls.py
{"filter":false,"title":"urls.py","tooltip":"/jobbank/urls.py","undoManager":{"mark":-1,"position":-1,"stack":[]},"ace":{"folds":[],"scrolltop":0,"scrollleft":0,"selection":{"start":{"row":16,"column":104},"end":{"row":16,"column":104},"isBackwards":false},"options":{"guessTabSize":true,"useWrapMode":false,"wrapToView":true},"firstLineState":{"row":27,"mode":"ace/mode/python"}},"timestamp":1432655973000,"hash":"1268939b788cb63685082438bf97f22cf69202d6"}

jb/urls.py
from django.conf.urls import patterns, url
from jb import views

urlpatterns = patterns('',
        
    #url(r'^job-bank/$', views.jobs_list), 
    #url(r'^submission-form/$', views.submission_form), 
    url(r'^submission-form/(?P<lang>[a-zA-Z]{2})/$', views.submission_form), 
    url(r'^job-detail/(?P<lang>[a-zA-Z]{2})/(?P<post_slug>[^/]+)/$', views.job_detail, name="job_detail"), 
    url(r'^edit-submission/(?P<lang>[a-zA-Z]{2})/(?P<uid>\w+)/$', views.edit_submission, name='edit_submission'),
)

jobbank/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from jb import views as jb_views
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'jobbank.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^jb/', include('jb.urls', namespace="jb")),
    url(r'^job-bank/(?P<lang>[a-zA-Z]{2})/$', jb_views.jobs_list),
    
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
)

jb/models.py
from django.db import models
from uuidfield import UUIDField
import datetime
#import itertools
#from django.utils.text import slugify
from encrypted_fields import EncryptedCharField
from import_export import resources, fields
from django.utils.translation import ugettext_lazy as _


LANGUAGES = (
	('en', 'English'),
	('fr', 'French')
)

CCTYPE = (
    ('visa', 'Visa'),
    ('mastercard', 'MasterCard')
)

EMPLOYMENT_TYPE = (
    ('Full-time', _('Full-time')),
    ('Part-time', _('Part-time'))
)

CONTRACT_TYPE = (
    ('Indeterminate/permanent', _('Indeterminate/permanent')),
    ('Term/contract', _('Term/contract')),
    ('Locum', _('Locum')),
)

POSITION_TYPE = (
    ('Academic', _('Academic')),
    ('Administrative', _('Administrative')),
    ('Obstetrics', _('Obstetrics')),
    ('Gynaecology', _('Gynaecology')),
    ('Obstetrics/Gynaecology', _('Obstetrics/Gynaecology')),
    ('Other', _('Other'))
)

RENEW_MONTHS = (
    (1, '1'),
    (2, '2'),
    (3, '3')
)


class Contact(models.Model):
    first_name = models.CharField(max_length=255, verbose_name=_('First Name'))
    last_name = models.CharField(max_length=255, verbose_name=_('Last Name'))
    email = models.CharField(max_length=254, verbose_name=_('Email'))
    phone = models.CharField(max_length=50, blank=True, verbose_name=_('Phone'))
    #ext = models.CharField(max_length=50, blank=True)
    address1 = models.CharField(max_length=255, verbose_name=_('Address 1'))
    address2 = models.CharField(max_length=255, blank=True, verbose_name=_('Address 2'))
    city = models.CharField(max_length=255, verbose_name=_('City'))
    province = models.CharField(max_length=255, verbose_name=_('Province / Territory / State'))
    country = models.CharField(max_length=255, verbose_name=_('Country'))
    postal_code = models.CharField(max_length=255, verbose_name=_('Postal Code'))
    company_name = models.CharField(max_length=255, blank=True, verbose_name=_('Company Name'))
    
    def __unicode__(self):
        string = unicode(self.first_name) + " " + unicode(self.last_name) 
        return string
	
class Payment(models.Model):
    posting_duration = models.IntegerField(null=True, choices=RENEW_MONTHS, verbose_name=_('Posting Duration (in months)'))
    ccType = models.CharField(max_length=50, choices=CCTYPE, verbose_name=_("Credit Card Type"))
    #ccNumber = fields.CreditCardField(max_length=255)
    ccNumber = EncryptedCharField(max_length=255, verbose_name=_("Credit Card Number"))
    ccHolderName = models.CharField(max_length=255, verbose_name=_("Name of Card Holder"))
    ccExpiry = models.DateField(verbose_name=_("Credit Card Expiry Date (mm/yy)"))
    ccSecurity = EncryptedCharField(max_length=50, verbose_name=_("Credit Card Security Code"))


class Submission(models.Model):
    uuid = UUIDField(auto=True)
    #position = models.OneToOneField(Position)
    contact = models.OneToOneField(Contact)
    payment = models.OneToOneField(Payment)
    show_contact = models.BooleanField(default=True, verbose_name=_("Show contact information in public posting"))
    language = models.CharField(max_length=50, choices=LANGUAGES, default='en')
    processed = models.BooleanField(default=False)
    #displayed = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now=False, auto_now_add=True) #auto_now_add for creation
    #date_created = models.DateTimeField(default=datetime.datetime.now) #default to make editable
    date_modified = models.DateTimeField(auto_now=True, auto_now_add=False) #auto_now_add for creation
    date_to_remove = models.DateField(null=True, verbose_name='Date of Removal')
    #position fields
    title = models.CharField(max_length=255, verbose_name=_("Position Title"))
    company_name = models.CharField(max_length=255, verbose_name=_('Company Name'))
    division = models.CharField(max_length=255, blank=True, verbose_name=_('Division'))
    reference_num = models.CharField(max_length=255, blank=True, verbose_name=_("Reference Number"))
    url = models.CharField(max_length=255, blank=True, verbose_name=_("Job Posting URL"))
    city = models.CharField(max_length=255, verbose_name=_('City'))
    province = models.CharField(max_length=255, verbose_name=_('Province/ Territory / State'))
    country = models.CharField(max_length=255, verbose_name=_('Country'))
    salary_min = models.IntegerField(max_length=50, default=0, blank=True, verbose_name=_("Salary Minimum"))
    salary_max = models.IntegerField(max_length=50, default=0, blank=True, verbose_name=_("Salary Maximum"))
    salary_details = models.CharField(max_length=255, blank=True, verbose_name=_('Salary Details'))
    salary_negotiable = models.BooleanField(default=False, verbose_name=_('Salary Negotiable'))
    employment_type = models.CharField(max_length=255, blank=True, choices=EMPLOYMENT_TYPE, verbose_name=_("Type of Employment"))
    contract_type = models.CharField(max_length=255, blank=True, choices=CONTRACT_TYPE, verbose_name=_("Type of Contract"))
    position_type = models.CharField(max_length=255, blank=True, choices=POSITION_TYPE, verbose_name=_("Type of Position"))
    job_summary = models.TextField(blank=True, verbose_name=_("Job Summary"))
    roles_responsibilities = models.TextField(blank=True, verbose_name=_("Roles and Responsibilities"))
    skills_competencies = models.TextField(blank=True, verbose_name=_("Skills and Competencies"))
    education_experience = models.TextField(blank=True, verbose_name=_("Education and Experience"))
    other = models.TextField(blank=True, verbose_name=_('Other'))
    start_date = models.DateField(blank=True, null=True, verbose_name=_("Start Date of Employment (dd/mm/yyyy)")) #change to text field in case "Immediate"
    deadline_date = models.DateField(blank=True, null=True, verbose_name=_("Deadline Date of Application (dd/mm/yyyy)"))
    slug = models.SlugField(unique=True, blank=True)
    
    # checks if the removal date has passed and returns True if so
    @property
    def is_past_due(self):
        if datetime.date.today() is not None and self.date_to_remove is not None:
            if datetime.date.today() > self.date_to_remove:
                return True
            return False
        else:
            return False
    
    def __unicode__(self):
		return unicode(self.title)


class Email(models.Model):
	code = models.CharField(max_length=50, blank=False, unique=True)
	title = models.CharField(max_length=255)
	body = models.TextField()
	description = models.CharField(max_length=255, blank=True, null=True)

	def __unicode__(self):
		#return unicode(self.id)
		return unicode(self.title)
		
		
class SubmissionResource(resources.ModelResource):

    amount = fields.Field()
    invoicing = fields.Field()
    contact = fields.Field()
    description = fields.Field()
    attention_to = fields.Field()
    
    def dehydrate_amount(self, obj):
		months = obj.payment.posting_duration
		
		if months == 1:
		    return "$300 + $39.00 = $339.00"
		elif months == 2:
		    return "$500 + $65.00 = $565.00"
		elif months == 3:
		    return "$700 + $91.00 = $791.00"
		else:
		    return "--"
		    
    def dehydrate_invoicing(self, obj):
        return "Job posting"
        
    def dehydrate_description(self, obj):
        return "%s / %s" % (obj.title, obj.company_name)
        
    def dehydrate_contact(self, obj):
        return "%s %s %s %s, %s %s %s" % (obj.contact.company_name, obj.contact.address1, obj.contact.address2, obj.contact.city, obj.contact.province, obj.contact.postal_code, obj.contact.phone )
    
    def dehydrate_attention_to(self, obj):
        return "%s %s" % (obj.contact.first_name, obj.contact.last_name)
        
    class Meta:
        model = Submission
        fields = ('', 'date_created', )
		
	

.c9/metadata/workspace/jb/forms.py
{"filter":false,"title":"forms.py","tooltip":"/jb/forms.py","undoManager":{"mark":7,"position":7,"stack":[[{"start":{"row":15,"column":130},"end":{"row":15,"column":131},"action":"insert","lines":[","],"id":1}],[{"start":{"row":15,"column":131},"end":{"row":15,"column":132},"action":"insert","lines":[" "],"id":2}],[{"start":{"row":15,"column":132},"end":{"row":15,"column":133},"action":"insert","lines":["'"],"id":3}],[{"start":{"row":15,"column":133},"end":{"row":15,"column":134},"action":"insert","lines":["s"],"id":4}],[{"start":{"row":15,"column":134},"end":{"row":15,"column":135},"action":"insert","lines":["l"],"id":5}],[{"start":{"row":15,"column":135},"end":{"row":15,"column":136},"action":"insert","lines":["u"],"id":6}],[{"start":{"row":15,"column":136},"end":{"row":15,"column":137},"action":"insert","lines":["g"],"id":7}],[{"start":{"row":15,"column":137},"end":{"row":15,"column":138},"action":"insert","lines":["'"],"id":8}]]},"ace":{"folds":[],"scrolltop":1.5,"scrollleft":0,"selection":{"start":{"row":5,"column":0},"end":{"row":5,"column":55},"isBackwards":true},"options":{"guessTabSize":true,"useWrapMode":false,"wrapToView":true},"firstLineState":0},"timestamp":1431713002000,"hash":"4138cc95977a028f1b637913905b48ada956dc24"}

jb/views.py
import itertools
from django.utils.text import slugify
from django.shortcuts import render
from django.shortcuts import render, render_to_response, redirect, get_object_or_404
from django.template import RequestContext, Context, Template
from jb.forms import PositionForm, ContactForm, PaymentForm
from jb.models import Submission, Email
from django.utils import translation
from django.utils.html import strip_tags, format_html
from django.core.mail import EmailMultiAlternatives, send_mail
import datetime



def activate_language(lang="en"):
	language = lang
	if language=="fr":
		translation.activate("fr")
	else:
		translation.activate("en")
	return language
	

def jobs_list(request, lang="en"):
    
    language = activate_language(lang)
        
    #get all submissions with displayed = True 
    #also need to automatically remove posts that are past the removal date (or check if it's past the date)
    
    displayed_jobs = Submission.objects.filter(processed=True)
    
    
    #filter jobs based on if it is past the removal date
    filtered_jobs = [job for job in displayed_jobs if not job.is_past_due]
    
    ## an alternate method to the above is to automatically change "processed" to False if the date is passed the removal date, upon calling the Submission

    return render(request, 'jb/mainlist.html', { 'jobs':filtered_jobs })
    
    
def job_detail(request, post_slug, lang="en"):
    
    language = activate_language(lang)
    
    the_submission = get_object_or_404(Submission, slug=post_slug)
    
    closed = False
    passed = the_submission.is_past_due
    processed = the_submission.processed
    
    if passed or not processed:
        closed = True
    
    return render(request, 'jb/jobdetail.html', { 'job':the_submission, 'closed':closed })
    


def submission_form(request, lang="en"):
    
    language = activate_language(lang)
	
    if request.method == 'POST':
        positionform = PositionForm(request.POST)
        contactform = ContactForm(request.POST)
        paymentform = PaymentForm(request.POST)

        if positionform.is_valid() and contactform.is_valid() and paymentform.is_valid() :
            
            new_contact = contactform.save()
            new_payment = paymentform.save()
            new_submission = positionform.save(commit=False)

            new_submission.slug = orig = slugify(new_submission.title)

            for x in itertools.count(1):
			    if not Submission.objects.filter(slug=new_submission.slug).exists():
				    break
			    new_submission.slug = '%s-%d' % (orig, x)

            new_submission.contact = new_contact
            new_submission.payment = new_payment
            new_submission.language = language
            new_submission.save()
            
            #uncomment these lines when in production
            
            '''
            if language == "fr":
                send_email(new_submission.contact, "sub-confirmation-FR", new_submission)
            else:
                send_email(new_submission.contact, "sub-confirmation", new_submission)
            '''
            return render(request, 'jb/thankyou.html', { 'job': new_submission } )
            
        else:
            return render(request, 'jb/submissionform.html', {'contactform':contactform, 'positionform': positionform, 'paymentform': paymentform })	
    else:
        contactform = ContactForm
        positionform = PositionForm
        paymentform = PaymentForm
        return render(request, 'jb/submissionform.html', { 'contactform': contactform, 'positionform': positionform, 'paymentform': paymentform })
        

def edit_submission(request, uid, lang="en"): 
    
    language = activate_language(lang)
    
    edit = True
    submission = get_object_or_404(Submission, uuid=uid)
    contact = submission.contact

    #check if one month has past from submission date, do not allow edit
    # http://stackoverflow.com/questions/4940583/subtract-dates-in-django
    today = datetime.datetime.today()
    today = today.replace(tzinfo=None)
    created = submission.date_created
    created = created.replace(tzinfo=None)
    
    dt = today - created
    days_diff = dt.days
    
    #msg = "today: " + str(today) + " ___ created: " + str(created) + "____ DIFF: " +  str(dt.days)
    
    if dt.days > 30:
        msg = "Editing submission is now closed. More than 30 days have passed since submission. %s days have passed. If you have any questions, please contact Linda Kollesh at lkollesh@sogc.com ." % days_diff
        return render(request, 'jb/message.html', { 'msg': msg, } )
    
    else:

        if request.method == "POST":
            positionform = PositionForm(request.POST, instance=submission)
            contactform = ContactForm(request.POST, instance=contact)

            if positionform.is_valid() and contactform.is_valid():
                contactform.save()
                this_submission = positionform.save(commit=False)
			    
                this_submission.date_modified = datetime.datetime.today()
                this_submission.save()
                
                return render(request, 'jb/thankyou.html', {'edit':edit, 'job': this_submission }) # send a variable to create custom message for edit
        
        else:
    		positionform = PositionForm(instance=submission)
    		contactform = ContactForm(instance=contact)

    return render_to_response("jb/editform.html", {'edit':edit, 'job':submission, 'positionform': positionform, 'contactform':contactform,  }, RequestContext(request))


def send_email(receiver, email_code, submission=None):
    
    the_email = Email.objects.get(code=str(email_code))
    the_content = the_email.body

    t = Template(the_content)
    c = Context({'contact': receiver, 'job': submission })

    html_content = t.render(c)
    text_content = strip_tags(html_content)

    subject, from_email = the_email.title, 'membership@sogc.com'
    to = receiver.email
    bcc_email = "lkollesh@sogc.com"
    msg = EmailMultiAlternatives(subject, text_content, from_email, [to], bcc=[bcc_email])	

    msg.attach_alternative(html_content, "text/html")
    msg.send()

templates/jb/editform.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}


{% block js %}

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script> 

<script>
     
    $(document).ready(function() {
        
        setFieldAttributes();
        
        //$("#id_posting_duration").attr("disabled", true); 
        $("#id_url").attr("placeholder", "www.yourcompany.com"); 

        $('form').h5Validate({
                errorClass:'error-select'
        });
        
     });
     
    function setFieldAttributes() 
    {
        $("#id_ccNumber").attr("pattern", "^(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\d{3})\d{11})$") 
        
        $('#id_ccNumber').attr("required", "true");
        $('#id_first_name').attr("required", "true");
        $('#id_last_name').attr("required", "true");
        $('#id_email').attr("required", "true");
        $('#id_phone').attr("required", "true");
        $('#id_city').attr("required", "true");
        $('#id_province').attr("required", "true");
        $('#id_postal_code').attr("required", "true");
        $('#id_address1').attr("required", "true");
        
        $('#id_company_name').attr("required", "true");
        $('#id_title').attr("required", "true");
        $('#id_country').attr("required", "true");
        //$('#id_employment_type').attr("required", "true");
        //$('#id_contract_type').attr("required", "true");
        //$('#id_position_type').attr("required", "true");
        //$('#id_posting_duration').attr("required", "true");
        
        $('#id_ccType').attr("required", "true");
        $('#id_ccNumber').attr("required", "true");
        $('#id_ccExpiry').attr("required", "true");
        $('#id_ccHolderName').attr("required", "true");
        $('#id_ccSecurity').attr("required", "true");
        
    }
     
</script>

{% endblock %}

{% block title %} {% trans "Job Submission Form" %}  {% endblock %}

 {% block errorlist %}
        {% if positionform.errors or contacform.errors %} 
            <div class="errorlist" >
                Please correct the error(s) below.
                
                {% for error in positionform.errors %}
                {{error}}
                {% endfor %}
                
                {% for error in contactform.errors %}
                {{error}}
                {% endfor %}
            </div>
        {% endif %}
  
{% endblock %}
            
            

{% block content %}

<form id="submissionForm" name="submissionForm" method="post">


<fieldset>
    <legend>{% trans "Contact Person - Person /Agency filling the form" %}</legend>


<div class="row">

<div class="twelve large-12 columns">
    <p>
    {{contactform.company_name.errors}}
    <label>{{contactform.company_name.label}}</label>
     {{contactform.company_name}} 
    </p>
</div>

</div>

<div class="row">
<div class="six large-6 columns">
    <p>
    {{contactform.first_name.errors}}
    <label><span class="star">*</span> {{contactform.first_name.label}}</label>
     {{contactform.first_name}} 
    </p>
</div>

<div class="six large-6 columns">
    <p>
    {{contactform.last_name.errors}}
    <label><span class="star">*</span> {{contactform.last_name.label}}</label>
     {{contactform.last_name}} 
     </p>
</div>
</div>

<div class="row">
<div class="six large-6 columns">
    <p>
    {{contactform.phone.errors}}
    <label><span class="star">*</span> {{contactform.phone.label}}</label>
     {{contactform.phone}} 
     </p>
</div>

<div class="six large-6 columns">
    <p>
    {{contactform.email.errors}}
    <label><span class="star">*</span> {{contactform.email.label}}</label>
     {{contactform.email}} 
     </p>
</div>
</div>

<div class="row">
<div class="six large-6 columns">
    <p>
    {{contactform.address1.errors}}
    <label><span class="star">*</span> {{contactform.address1.label}}</label>
     {{contactform.address1}} 
    </p>
</div>

<div class="six large-6 columns">
    <p>
    {{contactform.address2.errors}}
    <label>{{contactform.address2.label}}</label>
     {{contactform.address2}} 
    </p>
</div>
</div>

<div class="row">
<div class="six large-6 columns">
    <p>
    {{contactform.city.errors}}
    <label><span class="star">*</span> {{contactform.city.label}}</label>
     {{contactform.city}} 
    </p>
</div>

<div class="six large-6 columns">
    <p>
    {{contactform.province.errors}}
    <label><span class="star">*</span> {{contactform.province.label}}</label>
     {{contactform.province}} 
    </p>
</div>
</div>

<div class="row">
<div class="six large-6 columns">
    <p>
    {{contactform.country.errors}}
    <label><span class="star">*</span> {{contactform.country.label}}</label>
     {{contactform.country}} 
    </p>
</div>
<div class="six large-6 columns">
    <p>
    {{contactform.postal_code.errors}}
    <label><span class="star">*</span> {{contactform.postal_code.label}}</label>
     {{contactform.postal_code}} 
    </p>
</div>

</div>

<div class="row">
    <div class="twelve large-12 columns">
    <p>
        {{positionform.postal_code.errors}}
        <label>
        {{positionform.show_contact}}
        {{positionform.show_contact.label}}
        </label>
    </p>
        
    </div>
</div>

</fieldset>

<fieldset>
    <legend>{% trans "Position Information" %}</legend>


<div class="row">
<div class="eight large-8 columns">
     <p>
    {{positionform.company_name.errors}}
    <label><span class="star">*</span> {{positionform.company_name.label}}</label>
     {{positionform.company_name}} 
    </p>
</div>
<div class="four large-4 columns">
     <p>
    {{positionform.division.errors}}
    <label>{{positionform.division.label}}</label>
     {{positionform.division}} 
    </p>
</div>
</div>

<div class="row"</div>
<div class="four large-4 columns">
     <p>
    {{positionform.city.errors}}
    <label><span class="star">*</span> {{positionform.city.label}}</label>
     {{positionform.city}} 
    </p>
</div>
<div class="four large-4 columns">
     <p>
    {{positionform.province.errors}}
    <label><span class="star">*</span> {{positionform.province.label}}</label>
     {{positionform.province}} 
    </p>
</div>

<div class="four large-4 columns">
     <p>
    {{positionform.country.errors}}
    <label><span class="star">*</span> {{positionform.country.label}}</label>
     {{positionform.country}} 
    </p>
</div>
</div>

<div class="row">
<div class="eight large-8 columns">
    <p>
    {{positionform.title.errors}}
    <label><span class="star">*</span> {{positionform.title.label}}</label>
     {{positionform.title}} 
    </p>
</div>
<div class="four large-4 columns">
    <p>
    {{positionform.reference_num.errors}}
    <label>{{positionform.reference_num.label}}</label>
     {{positionform.reference_num}} 
    </p>
</div>
</div>

<div class="row">
<div class="twelve large-12 columns">
    <p>
    {{positionform.url.errors}}
    <label>{{positionform.url.label}}</label>
     {{positionform.url}} 
    </p>
</div>
</div>


<div class="row">
<div class="two large-2 columns">
    <p>
    {{positionform.salary_min.errors}}
    <label> {{positionform.salary_min.label}}</label>
     {{positionform.salary_min}} 
    </p>
</div>

<div class="two large-2 columns">
    <p>
    {{positionform.salary_max.errors}}
    <label>{{positionform.salary_max.label}}</label>
     {{positionform.salary_max}} 
    </p>
</div>

<div class="five large-5 columns">
    <p>
    {{positionform.salary_details.errors}}
    <label>{{positionform.salary_details.label}}</label>
     {{positionform.salary_details}} 
    </p>
</div>

<div class="three large-3 columns">
    <p>
      <br />
    {{positionform.salary_negotiable.errors}}
    <label>{{positionform.salary_negotiable.label}}</label>
     {{positionform.salary_negotiable}} 
    </p>
</div>
</div>

<div class="row">
<div class="twelve large-12 columns">
    <p>
     {{positionform.employment_type.errors}}
    <label> {{positionform.employment_type.label}} </label>
    {{positionform.employment_type}}
    </p>
</div>
</div>

<div class="row">
<div class="twelve large-12 columns">
    <p>
     {{positionform.contract_type.errors}}
    <label>{{positionform.contract_type.label}} </label>
    {{positionform.contract_type}}
    </p>
</div>
</div>

<div class="row">
<div class="twelve large-12 columns">
    <p>
     {{positionform.position_type.errors}}
    <label>{{positionform.position_type.label}} </label>
    {{positionform.position_type}}
    </p>
</div>
</div>

<div class="row">
<div class="twelve large-12 columns">
    <p>
     {{positionform.job_summary.errors}}
    <label> {{positionform.job_summary.label}} </label>
    {{positionform.job_summary}}
    </p>
</div>
</div>

<div class="row">
<div class="twelve large-12 columns">
    <p>
     {{positionform.roles_responsibilities.errors}}
    <label> {{positionform.roles_responsibilities.label}} </label>
    {{positionform.roles_responsibilities}}
    </p>
</div>
</div>

<div class="row">
<div class="twelve large-12 columns">
    <p>
     {{positionform.skills_competencies.errors}}
    <label> {{positionform.skills_competencies.label}} </label>
    {{positionform.skills_competencies}}
    </p>
</div>
</div>

<div class="row">
<div class="twelve large-12 columns">
    <p>
     {{positionform.education_experience.errors}}
    <label> {{positionform.education_experience.label}} </label>
    {{positionform.education_experience}}
    </p>
</div>
</div>

<div class="row">
<div class="twelve large-12 columns">
    <p>
     {{positionform.other.errors}}
    <label> {{positionform.other.label}} </label>
    {{positionform.other}}
    </p>
</div>
</div>

<div class="row">
<div class="twelve large-12 columns">
    <p>
     {{positionform.start_date.errors}}
    <label> {{positionform.start_date.label}} </label>
    {{positionform.start_date}}
    </p>
</div>
</div>

<div class="row">
<div class="twelve large-12 columns">
    <p>
     {{positionform.deadline_date.errors}}
    <label> {{positionform.deadline_date.label}} </label>
    {{positionform.deadline_date}}
    </p>
</div>
</div>


<div class="row">
<div class="twelve large-12 columns">
    <p>
     {{positionform.posting_duration.errors}}
    <label> {{positionform.posting_duration.label}} </label>
    {{positionform.posting_duration}}
    </p>
</div>
</div>
 

    {% csrf_token %}
</fieldset>


{% csrf_token %}

<input class="small button" type="submit" value="{% trans 'Submit' %}" />
</form> 
 
{% endblock content %}


{% block jsbottom %}

    <script src="{% static 'jb/js/h5validate.js' %}"></script>

{% endblock %}